title: "Portfolio"
author: "Hà Xuân Kiệt"
email: "haxuankiet250@gmail.com"
description: "Data Analyst"
github_username: HaXuanKiet250

show_downloads: true
theme: jekyll-theme-minimal

logo: "portfolio/IMG_2528.JPG"

social:
  github: "https://github.com/HaXuanKiet250"
  linkedin: "www.linkedin.com/in/haxuankiet"
