title: "Portfolio"
author: "Hà Xuân Kiệt"
email: "haxuankiet250@gmail.com"
description: "Data Analyst"
github_username: HaXuanKiet250/portfolio
linkedin_username: your-linkedin
show_downloads: true
theme: jekyll-theme-minimal
