title: "Portfolio"
author: "Hà Xuân Kiệt"
email: "haxuankiet250@gmail.com"
description: "Data Analyst | IoT & Smart Devices Enthusiast"
github_username: HaXuanKiet250
linkedin_username: your-linkedin
show_downloads: true
theme: jekyll-theme-minimal
